backend:
  name: proxy
  proxy_url: http://localhost:8081/api/v1
  branch: master

local_backend: true

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "showcase"
    label: "Showcase Widgets"
    folder: "src/showcase"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Published",
          name: "published",
          widget: "boolean",
          default: true,
        }
      - { label: "Date", name: "date", widget: "datetime" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["Tutorial", "Demo", "Reference"],
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          default: ["decap", "demo"],
        }
      - {
          label: "Rating",
          name: "rating",
          widget: "number",
          value_type: "int",
          min: 1,
          max: 5,
          step: 1,
        }
      - {
          label: "Cover Image",
          name: "cover",
          widget: "image",
          required: false,
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: false,
        }
      - { label: "Content", name: "body", widget: "markdown" }
